apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS  # Change this to your desired SKU (e.g., Standard_LRS, Premium_LRS)
allowVolumeExpansion: true