# Define the Container port
containerPort: 8000

# Define number of pods
replicas: 3

# Define image details for your frontend application
image:
  repository: yogendrakokamkar/python-sample-app-demo
  tag: v1
  pullPolicy: IfNotPresent

# Define port and targetPort for your service
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30007
